##Stage 1
FROM node:10.23.3-alpine AS builder
MAINTAINER pranav.dhope@gmail.com

WORKDIR /app
COPY package.json .
RUN npm install

COPY . .
RUN npm run build --prod

##Stage 2
FROM httpd:alpine
COPY --from=builder /app/dist/AngularApp /usr/share/nginx/html
